spring:
  application:
    name: hilite
  profiles:
    active: private
  jpa:
    open-in-view: false
  main:
    web-application-type: servlet
logging:
  level:
    root: info
    org.example: debug
    org.springframework.security: debug
