# src/main/resources/application-ci.yml
# CI/CD 환경에서 사용하는 설정 파일

spring:
  datasource:
    # H2 인메모리 데이터베이스 사용 (CI 환경에서 빠른 테스트를 위해)
    url: jdbc:h2:mem:cidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      # CI 환경에서는 매번 새로 생성
      ddl-auto: create-drop
    # CI에서는 SQL 로그 최소화 (성능 향상)
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # H2를 MySQL 호환 모드로 사용
        dialect: org.hibernate.dialect.H2Dialect
        # 배치 처리 최적화
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  h2:
    console:
      # CI 환경에서는 H2 콘솔 비활성화
      enabled: false

# JWT 설정 (CI 환경용 고정값)
jwt:
  secret: ci-test-jwt-secret-key-for-github-actions-testing-only-not-for-production

# Swagger 설정 (CI에서는 비활성화)
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
