spring:
  # R2DBC 설정 (H2 메모리 DB)
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    pool:
      initial-size: 1
      max-size: 5

  main:
    web-application-type: reactive

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data-test.sql  # 테스트용 데이터
      continue-on-error: false

jwt:
  secret: test-jwt-secret-for-testing-test-jwt-secret-for-testing-test-jwt-secret-for-testing

# 로깅 설정 (테스트 환경용 - 상세 로깅)
logging:
  level:
    root: INFO
    org.example: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.core.env: TRACE
    org.springframework.security: DEBUG
    # R2DBC 상세 로깅
    io.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    # 쿼리 로깅
    io.r2dbc.h2: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"