name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up application-private.yml from GitHub Secrets
        run: |
            echo "spring.datasource.url=jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" >> src/main/resources/application-private.yml
            echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> src/main/resources/application-private.yml
            echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application-private.yml
            echo "jwt.secret=${{ secrets.JWT_SECRET }}" >> src/main/resources/application-private.yml

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run Spotless
        run: ./gradlew spotlessCheck

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build
